spring:
  application:
    name: daisy-azure-storage
  cloud:
    azure:
      storage:
        blob:
          account-name: {AZURE_STORAGE_ACCOUNT_NAME}
          account-key: {AZURE_STORAGE_ACCOUNT_KEY}
          container-name: {AZURE_STORAGE_CONTAINER_NAME}